server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 132.226.64.96:8848
        username: nacos
        password: nacos
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.153.245.177:3306/carbondate?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&maxReconnects=3&initialTimeout=10&connectTimeout=60000&socketTimeout=300000&allowPublicKeyRetrieval=true
    username: xueerze
    password: 123456
    hikari:
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      connection-test-query: SELECT 1
      validation-timeout: 3000
      keepalive-time: 300000
  data:
    redis:
      host: 132.226.64.96
      port: 6379
      password: 20041122gooder
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
